/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_AD_25 (coord M15), LPUART1_RXD/J32[2] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_LPUART1_RXD_PERIPHERAL                  LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_LPUART1_RXD_SIGNAL                          RXD   /*!< Signal name */

/* GPIO_AD_24 (coord L13), LPUART1_TXD/J31[2] */
/* Routed pin properties */
#define BOARD_INITDEBUG_UARTPINS_LPUART1_TXD_PERIPHERAL                  LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UARTPINS_LPUART1_TXD_SIGNAL                          TXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);          /* Function assigned for the Cortex-M7F */

/* GPIO_SD_B1_05 (coord A16), SD1_D3/J15[2]/WIFI_SDIO_D3/J54[19] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_D3_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_D3_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHCPINS_SD1_D3_CHANNEL                                    3U   /*!< Signal channel */

/* GPIO_SD_B1_04 (coord B15), SD1_D2/J15[1]/WIFI_SDIO_D2/J54[17] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_D2_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_D2_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHCPINS_SD1_D2_CHANNEL                                    2U   /*!< Signal channel */

/* GPIO_SD_B1_03 (coord B17), SD1_D1/J15[8]/WIFI_SDIO_D1/J54[15] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_D1_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_D1_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHCPINS_SD1_D1_CHANNEL                                    1U   /*!< Signal channel */

/* GPIO_SD_B1_02 (coord C15), SD1_D0/J15[7]/WIFI_SDIO_D0/J54[13]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_D0_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_D0_SIGNAL                             usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHCPINS_SD1_D0_CHANNEL                                    0U   /*!< Signal channel */

/* GPIO_SD_B1_00 (coord B16), SD1_CMD/J15[3]/WIFI_SDIO_CMD/J54[11]/NVCC_SD/U19G[D14] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_CMD_PERIPHERAL                            USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_CMD_SIGNAL                             usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B1_01 (coord D15), SD1_CLK/J15[5]/WIFI_SDIO_CLK/J54[9] */
/* Routed pin properties */
#define BOARD_INITUSDHCPINS_SD1_CLK_PERIPHERAL                            USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHCPINS_SD1_CLK_SIGNAL                             usdhc_clk   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSDHCPins(void);               /* Function assigned for the Cortex-M7F */

/* GPIO_AD_02 (coord R13), SIM1_RST/J57[5]/J44[C2]/LCD_RST_B/J48[21]/J25[11]/J10[6] */
/* Routed pin properties */
#define BOARD_INITARDUINOUARTPINS_SIM1_RST_PERIPHERAL                    LPUART7   /*!< Peripheral name */
#define BOARD_INITARDUINOUARTPINS_SIM1_RST_SIGNAL                          CTS_B   /*!< Signal name */

/* GPIO_AD_03 (coord P15), SIM1_SVEN/J57[2]/Flash_RST/U21[B2]/J25[9]/J10[8] */
/* Routed pin properties */
#define BOARD_INITARDUINOUARTPINS_SIM1_SVEN_PERIPHERAL                   LPUART7   /*!< Peripheral name */
#define BOARD_INITARDUINOUARTPINS_SIM1_SVEN_SIGNAL                         RTS_B   /*!< Signal name */

/* GPIO_AD_00 (coord N12), SIM1_TRXD/J44[C7]/J57[9]/CTP_INT/J48[29]/J25[15]/J9[14] */
/* Routed pin properties */
#define BOARD_INITARDUINOUARTPINS_SIM1_TRXD_PERIPHERAL                   LPUART7   /*!< Peripheral name */
#define BOARD_INITARDUINOUARTPINS_SIM1_TRXD_SIGNAL                           TXD   /*!< Signal name */

/* GPIO_AD_01 (coord R14), SIM1_CLK/J44[C3]/J57[7]/CTP_RST_B/J48[28]/J10[4]/J25[13] */
/* Routed pin properties */
#define BOARD_INITARDUINOUARTPINS_SIM1_CLK_PERIPHERAL                    LPUART7   /*!< Peripheral name */
#define BOARD_INITARDUINOUARTPINS_SIM1_CLK_SIGNAL                            RXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitArduinoUARTPins(void);         /* Function assigned for the Cortex-M7F */

/* GPIO_SD_B2_05 (coord E14), FlexSPI_A_DQS/U21[C3] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_DQS_PERIPHERAL                      FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_DQS_SIGNAL                     FLEXSPI_A_DQS   /*!< Signal name */

/* GPIO_SD_B2_06 (coord F17), FlexSPI_A_SS0/U23[1]/U21[C2] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_SS0_PERIPHERAL                      FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_SS0_SIGNAL                   FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_SD_B2_07 (coord G14), FlexSPI_A_CLK/U23[6]/U21[B2] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_CLK_PERIPHERAL                      FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_CLK_SIGNAL                    FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B2_08 (coord F15), FlexSPI_A_D0/U23[5]/U21[D3] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_D0_PERIPHERAL                       FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_D0_SIGNAL                    FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B2_09 (coord H15), FlexSPI_A_D1/U23[2]/U21[D2] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_D1_PERIPHERAL                       FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_D1_SIGNAL                    FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B2_10 (coord H14), FlexSPI_A_D2/U23[3]/U21[C4] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_D2_PERIPHERAL                       FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_D2_SIGNAL                    FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B2_11 (coord F16), FlexSPI_A_D3/U23[7]/U21[D4] */
/* Routed pin properties */
#define BOARD_INITSPIPINS_FlexSPI_A_D3_PERIPHERAL                       FLEXSPI1   /*!< Peripheral name */
#define BOARD_INITSPIPINS_FlexSPI_A_D3_SIGNAL                    FLEXSPI_A_DATA3   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins(void);                 /* Function assigned for the Cortex-M7F */

/* GPIO_AD_34 (coord J16), 1588_EVENT0_IN/SD1_VSELECT */
/* Routed pin properties */
#define BOARD_INITM2UARTPINS_SD1_VSELECT_PERIPHERAL                     LPUART10   /*!< Peripheral name */
#define BOARD_INITM2UARTPINS_SD1_VSELECT_SIGNAL                            CTS_B   /*!< Signal name */

/* GPIO_AD_35 (coord G17), 1588_EVENT0_OUT/SD_PWREN_B */
/* Routed pin properties */
#define BOARD_INITM2UARTPINS_SD_PWREN_B_PERIPHERAL                      LPUART10   /*!< Peripheral name */
#define BOARD_INITM2UARTPINS_SD_PWREN_B_SIGNAL                             RTS_B   /*!< Signal name */

/* GPIO_AD_33 (coord H17), ENET_MDIO/U7[11] */
/* Routed pin properties */
#define BOARD_INITM2UARTPINS_ENET_MDIO_PERIPHERAL                       LPUART10   /*!< Peripheral name */
#define BOARD_INITM2UARTPINS_ENET_MDIO_SIGNAL                                RXD   /*!< Signal name */

/* GPIO_AD_32 (coord K16), ENET_MDC/U7[12]/SD1_CD_B/J15[9] */
/* Routed pin properties */
#define BOARD_INITM2UARTPINS_ENET_MDC_PERIPHERAL                        LPUART10   /*!< Peripheral name */
#define BOARD_INITM2UARTPINS_ENET_MDC_SIGNAL                                 TXD   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitM2UARTPins(void);              /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitM2WifiResetPins(void);         /* Function assigned for the Cortex-M7F */

/* GPIO_AD_21 (coord K14), SAI1_TXD[0]/J9[9]/J62[1]/BT_PCM_TXD/U16[9]/U354[6] */
/* Routed pin properties */
#define BOARD_INITM2SCOPINS_BT_PCM_TXD_PERIPHERAL                           SAI1   /*!< Peripheral name */
#define BOARD_INITM2SCOPINS_BT_PCM_TXD_SIGNAL                      sai_tx_data00   /*!< Signal name */

/* GPIO_AD_22 (coord K12), SAI1_TX_BCLK/J9[11]/BT_PCM_BCLK/U16[11]/U354[7]/U355[17] */
/* Routed pin properties */
#define BOARD_INITM2SCOPINS_BT_PCM_BCLK_PERIPHERAL                          SAI1   /*!< Peripheral name */
#define BOARD_INITM2SCOPINS_BT_PCM_BCLK_SIGNAL                       sai_tx_bclk   /*!< Signal name */

/* GPIO_AD_23 (coord J12), SAI1_TX_SYNC/J9[13]/BT_PCM_SYNC/U16[8]/U354[8]/U355[16] */
/* Routed pin properties */
#define BOARD_INITM2SCOPINS_BT_PCM_SYNC_PERIPHERAL                          SAI1   /*!< Peripheral name */
#define BOARD_INITM2SCOPINS_BT_PCM_SYNC_SIGNAL                       sai_tx_sync   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitM2ScoPins(void);               /* Function assigned for the Cortex-M7F */

/* GPIO_LPSR_05 (coord N8), I2C5_SCL/J48[27]/U32[17]/U34[4]/J10[20] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_I2C5_SCL_PERIPHERAL                         LPI2C5   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_I2C5_SCL_SIGNAL                                SCL   /*!< Signal name */

/* GPIO_LPSR_04 (coord N7), I2C5_SDA/J48[26]/U32[18]/U34[6]/J10[18] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_I2C5_SDA_PERIPHERAL                         LPI2C5   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_I2C5_SDA_SIGNAL                                SDA   /*!< Signal name */

/* GPIO_EMC_B2_04 (coord M1), SEMC_D20/U25[8] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_SEMC_D20_PERIPHERAL                           SAI2   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_SEMC_D20_SIGNAL                           sai_mclk   /*!< Signal name */

/* GPIO_EMC_B2_07 (coord M3), SEMC_D23/U25[13] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_SEMC_D23_PERIPHERAL                           SAI2   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_SEMC_D23_SIGNAL                        sai_rx_data   /*!< Signal name */

/* GPIO_EMC_B2_10 (coord R2), SEMC_D25/U25[44] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_SEMC_D25_PERIPHERAL                           SAI2   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_SEMC_D25_SIGNAL                        sai_tx_sync   /*!< Signal name */

/* GPIO_EMC_B2_09 (coord N2), SEMC_D24/U25[42] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_SEMC_D24_PERIPHERAL                           SAI2   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_SEMC_D24_SIGNAL                        sai_tx_bclk   /*!< Signal name */

/* GPIO_EMC_B2_08 (coord P1), SEMC_DM2/U25[15] */
/* Routed pin properties */
#define BOARD_INITM2CODECPINS_SEMC_DM2_PERIPHERAL                           SAI2   /*!< Peripheral name */
#define BOARD_INITM2CODECPINS_SEMC_DM2_SIGNAL                        sai_tx_data   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitM2CodecPins(void);             /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
